  
# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/staging/vault.yml

wordpress_sites:
  staging.platefit.co:
    site_hosts:
      - canonical: staging.platefit.co
    local_path: ../ # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:manticarodrigo/platefit.git # replace with your Git repo URL
    branch: staging
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: false